# Generated by Django 2.1.3 on 2018-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('seria', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('heating', models.IntegerField()),
            ],
        ),
    ]
